<a href="https://colab.research.google.com/github/Thierno-dev/MachineLearningApprentissage/blob/main/ManipulationDataMachinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


Manipulation donnees avec tensorflow

In [7]:
x = tf.range(12,dtype=tf.float32) #creation d'un tableau de valeur



#Redimensionner les données

X = tf.reshape(x,(-1,3)) #creation d'une matrice de taille n avec cible(h,w) donc w=n/h

tf.size(x), X


(<tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=float32)>)

Creation de matrices

In [16]:
X_zero = tf.zeros((3,2,4))#Creation d'une matrice avec zeros

X_one = tf.ones((2,3))

X_zero,X_one

(<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

Ajouter la normale des valeurs dans le tensorflow en normalisant la valeur en utilisant la distribution gaussienne comme Numpy np.random.randn

In [19]:
X_normal = tf.random.normal((3,10))

X_normal, X_normal[-1], X_normal[1:3]

(<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
 array([[ 1.0992192 ,  1.956105  ,  1.9078206 , -1.4317052 ,  0.6650361 ,
          0.3344601 ,  1.7115843 , -1.8734303 , -1.3224658 , -0.783093  ],
        [-1.2758174 ,  1.2479209 , -1.8499901 ,  1.1200445 , -1.3715289 ,
          1.9353851 , -0.17514135,  0.85679734, -0.07549052, -0.90636206],
        [-1.4861633 , -0.58357537, -0.98928493,  0.5980755 , -0.82055074,
          0.32355648,  0.35054827, -0.20530121, -0.5165443 , -1.0632151 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([-1.4861633 , -0.58357537, -0.98928493,  0.5980755 , -0.82055074,
         0.32355648,  0.35054827, -0.20530121, -0.5165443 , -1.0632151 ],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 10), dtype=float32, numpy=
 array([[-1.2758174 ,  1.2479209 , -1.8499901 ,  1.1200445 , -1.3715289 ,
          1.9353851 , -0.17514135,  0.85679734, -0.07549052, -0.90636206],
        [-1.4861633 , -0.58357537, -0.98928493,  0.5980755 ,

Attributions de valeurs

In [20]:
X_vars = tf.Variable(X_normal)

X_vars[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 10) dtype=float32, numpy=
array([[ 1.0992192 ,  1.956105  ,  1.9078206 , -1.4317052 ,  0.6650361 ,
         0.3344601 ,  1.7115843 , -1.8734303 , -1.3224658 , -0.783093  ],
       [-1.2758174 ,  1.2479209 ,  9.        ,  1.1200445 , -1.3715289 ,
         1.9353851 , -0.17514135,  0.85679734, -0.07549052, -0.90636206],
       [-1.4861633 , -0.58357537, -0.98928493,  0.5980755 , -0.82055074,
         0.32355648,  0.35054827, -0.20530121, -0.5165443 , -1.0632151 ]],
      dtype=float32)>

Operations données

In [23]:
X_unaire = tf.exp(X_normal) # f: R->R

#Operations entre deux vecteurs

x = tf.constant([1.0,6.7,4,8])
y = tf.constant([1.0,6.7,4,8])

x+y, x-y,x*y,x / y, x**y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2. , 13.4,  8. , 16. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.      , 44.889996, 16.      , 64.      ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([1.0000000e+00, 3.4253184e+05, 2.5600000e+02, 1.6777216e+07],
       dtype=float32)>)

Lecture des données

In [25]:
!pip install ucimlrepo

Importation de données

In [26]:
from ucimlrepo import fetch_ucirepo

Voir les données avec  L'imputation remplace les valeurs manquantes par des estimations de leurs valeurs, tandis que la suppression élimine simplement les lignes ou les colonnes contenant des valeurs manquantes.

In [54]:
# fetch dataset
abalone = fetch_ucirepo(id=1)

# data (as pandas dataframes)
X = abalone.data.features #seperation des données en 2 partie X et le Y puis traitement des données numerique
y = abalone.data.targets

pd.isna(X)
# metadata
#print(abalone.metadata)

# variable information
#print(abalone.variables)

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0     False   False     False   False         False           False   
1     False   False     False   False         False           False   
2     False   False     False   False         False           False   
3     False   False     False   False         False           False   
4     False   False     False   False         False           False   
...     ...     ...       ...     ...           ...             ...   
4172  False   False     False   False         False           False   
4173  False   False     False   False         False           False   
4174  False   False     False   False         False           False   
4175  False   False     False   False         False           False   
4176  False   False     False   False         False           False   

      Viscera_weight  Shell_weight  
0              False         False  
1              False         False  
2              False         False  
3              False         False  
4              False         False  
...              ...           ...  
4172           False         False  
4173           False         False  
4174           False         False  
4175           False         False  
4176           False         False  

[4177 rows x 8 columns]

Conversion en mode tensor flow

Traitement des donnee sexe

In [58]:
X = pd.get_dummies(X, dummy_na=True)#ceci rend les données toute numerique


Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0      0.455     0.365   0.095        0.5140          0.2245          0.1010   
1      0.350     0.265   0.090        0.2255          0.0995          0.0485   
2      0.530     0.420   0.135        0.6770          0.2565          0.1415   
3      0.440     0.365   0.125        0.5160          0.2155          0.1140   
4      0.330     0.255   0.080        0.2050          0.0895          0.0395   
...      ...       ...     ...           ...             ...             ...   
4172   0.565     0.450   0.165        0.8870          0.3700          0.2390   
4173   0.590     0.440   0.135        0.9660          0.4390          0.2145   
4174   0.600     0.475   0.205        1.1760          0.5255          0.2875   
4175   0.625     0.485   0.150        1.0945          0.5310          0.2610   
4176   0.710     0.555   0.195        1.9485          0.9455          0.3765   

      Shell_weight  Sex_F  Sex_I  Sex_M  Sex_nan  
0           0.1500      0      0      1        0  
1           0.0700      0      0      1        0  
2           0.2100      1      0      0        0  
3           0.1550      0      0      1        0  
4           0.0550      0      1      0        0  
...            ...    ...    ...    ...      ...  
4172        0.2490      1      0      0        0  
4173        0.2605      0      0      1        0  
4174        0.3080      0      0      1        0  
4175        0.2960      1      0      0        0  
4176        0.4950      0      0      1        0  

[4177 rows x 11 columns]

Eliminer les champs vide

In [59]:
X = X.fillna(X.mean())#Rempli les champs par les valeurs des champs moyenne du groupe

X

Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0      0.455     0.365   0.095        0.5140          0.2245          0.1010   
1      0.350     0.265   0.090        0.2255          0.0995          0.0485   
2      0.530     0.420   0.135        0.6770          0.2565          0.1415   
3      0.440     0.365   0.125        0.5160          0.2155          0.1140   
4      0.330     0.255   0.080        0.2050          0.0895          0.0395   
...      ...       ...     ...           ...             ...             ...   
4172   0.565     0.450   0.165        0.8870          0.3700          0.2390   
4173   0.590     0.440   0.135        0.9660          0.4390          0.2145   
4174   0.600     0.475   0.205        1.1760          0.5255          0.2875   
4175   0.625     0.485   0.150        1.0945          0.5310          0.2610   
4176   0.710     0.555   0.195        1.9485          0.9455          0.3765   

      Shell_weight  Sex_F  Sex_I  Sex_M  Sex_nan  
0           0.1500      0      0      1        0  
1           0.0700      0      0      1        0  
2           0.2100      1      0      0        0  
3           0.1550      0      0      1        0  
4           0.0550      0      1      0        0  
...            ...    ...    ...    ...      ...  
4172        0.2490      1      0      0        0  
4173        0.2605      0      0      1        0  
4174        0.3080      0      0      1        0  
4175        0.2960      1      0      0        0  
4176        0.4950      0      0      1        0  

[4177 rows x 11 columns]

In [60]:
X = tf.constant(X.to_numpy(dtype=float))

y = tf.constant(y.to_numpy(dtype=float))

X

<tf.Tensor: shape=(4177, 11), dtype=float64, numpy=
array([[0.455, 0.365, 0.095, ..., 0.   , 1.   , 0.   ],
       [0.35 , 0.265, 0.09 , ..., 0.   , 1.   , 0.   ],
       [0.53 , 0.42 , 0.135, ..., 0.   , 0.   , 0.   ],
       ...,
       [0.6  , 0.475, 0.205, ..., 0.   , 1.   , 0.   ],
       [0.625, 0.485, 0.15 , ..., 0.   , 0.   , 0.   ],
       [0.71 , 0.555, 0.195, ..., 0.   , 1.   , 0.   ]])>